api = "2"
core="7.x"

dependencies[] = "ctools"
dependencies[] = "date"
dependencies[] = "features"
dependencies[] = "field_group"
dependencies[] = "image"
dependencies[] = "link"
dependencies[] = "pushtape_core"
dependencies[] = "options"
dependencies[] = "page_manager"
dependencies[] = "panelizer"
dependencies[] = "strongarm"
dependencies[] = "taxonomy"
dependencies[] = "views"