<?php
/**
 * @file
 * Code for the Pushtape Events feature.
 */

include_once('pushtape_events.features.inc');


/**
 * Implementation of hook_apps_app_info()
 */
function pushtape_events_apps_app_info() {
  return array(
    'demo content module' => 'pushtape_events_democontent',
    'configure form' => 'pushtape_events_configure_form',
  );
}


/** 
 * Pushtape Events App Configuration Form
 *
 * This form will be blank until we have specific settings to customize beyond
 * the demo content that the apps.module puts here for us. 
 */
function pushtape_events_configure_form($form, &$form_state) {
  $form = array();

   return $form;
}
