api = "2"
core="7.x"

projects[] = "ctools"
projects[] = "date"
projects[] = "features"
projects[] = "field_group"
projects[] = "link"
projects[] = "strongarm"
projects[] = "taxonomy"
projects[] = "views"